### ISSUE TITLE
what board should I use for platformio?

### ISSUE THREAD

**Issue by dutchsnowden** [GroundStudio/GroundStudio_Carbon_S2#1]
If I want to develop in Platformio, what board should I use?

**Comment by victor1115** [comment]
We can only help to get you started on Arduino IDE for wich you can find some setup example to control the onboard RGB led in the development board page:

https://ardushop.ro/ro/home/2063-placa-de-dezvoltare-carbon-s2.html

For the moment we do not have enough resources to provide support for the Platformio environment.
